### PR TITLE
Added default.js proposal

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR adds information on the proposal of a `default.js` with all the edge cases.

### CODE REVIEW

**Comment by zenparsing** [comment]
Thanks, I'll take a close look a little later today.

**Comment by martinheidegger** [comment]
@zenparsing I merged the PR before your review (since my time is limited). Please send a PR with fixes if you find things to be inaccurate.

**Comment by zenparsing** [comment]
Great. Thank you. I've had an extreme dearth of free time lately, but it looked good when I scanned it earlier.

**Comment by martinheidegger** [comment]
Also added `default.js` as option here: https://www.wedgies.com/preview/question/574e872600f88e18001b3dc0

**Pull request merged**
